apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-fleet-orchestrator
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/kuldeepmindpath07/hub-spoke-gitops.git'
        revision: HEAD
        files:
          - path: "tenants/*/config.yaml"
  template:
    metadata:
      name: 'tenant-{{tenantId}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/kuldeepmindpath07/hub-spoke-gitops.git'
        targetRevision: HEAD
        path: 'tenants/{{tenantId}}'
      destination:
        name: '{{cluster}}'
        namespace: 'tenant-{{tenantId}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true