apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-fleet-orchestrator
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          # Generator 1: Scans Git for new tenant folders
          - git:
              repoURL: 'https://github.com/kuldeepmindpath07/hub-spoke-gitops.git'
              revision: HEAD
              directories:
                - path: tenants/*
          # Generator 2: Queries the Hub API for matching Tenant placements
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'tenant-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/kuldeepmindpath07/hub-spoke-gitops.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        # 🎯 THE FIX: Maps the destination cluster dynamically based on 
        # what the cluster inventory name returns
        name: '{{name}}' 
        namespace: 'tenant-{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true