apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: socketio-gateway
    tenant: '508'
  name: socketio-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: socketio-gateway
  template:
    metadata:
      labels:
        app: socketio-gateway
    spec:
      containers:
      - image: nginx:alpine
        name: gateway-pod
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
